name: InventoryProtector
version: '${project.version}'
main: net.daechler.inventoryprotector.InventoryProtector
api-version: 1.19
authors: [ Daechler ]
description: If a player dies, and it was not caused by another player, they keep their inventory.
