name: InventoryProtector
version: '${project.version}'
main: net.daechler.inventoryprotector.InventoryProtector
api-version: 1.19
authors: [ Daechler ]
description: This plugin ensures that if a player dies and this was not caused by another player, he keeps his inventory.
